apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
  labels:
    app: online-inference-resources
spec:
  containers:
    - image: maksima1ist/online_inference:1.0.2
      name: online-inference-resources  
      ports:
        - containerPort: 5000
      resources:
        requests:
          memory: "1Gi"
          cpu: "100m"
        limits:
          memory: "3Gi"
          cpu: "300m"